[package]
name = "Montagne"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["tokio", "markdown"]}
open = "5.3.2"
rfd = "0.15.3"
tokio = {version = "1.45.0", features = ["fs"]}
